Microverse Tasks
VelzckC0D3/Hello-Microverse pull request #1
Opened 2023-02-14 21:47 UTC by VelzckC0D3

I have successfully completed the tasks that were requested within the program. I double-checked on all Linters, which include Stylelint, Webhint, and Lighthouse, to ensure that the code meets the required standards. Additionally, I have added basic styling to the website and personalized the README.md file to enhance its appearance and make it more informative.

2023-02-14 22:02 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :

Hi @VelzckC0D3 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights :tophat:  :+1: 
- Linters are running well :+1: 
- Good use of Github flow :+1: 

## Required Changes ♻️
- [ ] :thinking: As per the project requirements, kindly make sure to create a test.md file and add it to gitignore
- [ ] It would be better to use this [template](https://github.com/microverseinc/readme-template) to create your custom README file as requested in the project requirements [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md#:~:text=Add%20descriptive%20README%20file%20to%20your%20project%20%2D%20please%20use%20this%20template%20but%20remember%20to%20customize%20it%20to%20your%20project.), assuming that the only optional section is the FAQ/
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 23:21 UTC, NahnahAJ requested changes
Hi @VelzckC0D3 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.
<img src="https://media0.giphy.com/media/L422JoNlBBBD42zkQ9/giphy.gif"/>

 ## Highlights
- [ ] Good use of GitHub flow :heavy_check_mark: 
- [ ] Nice Live Demo :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 23:21 UTC, NahnahAJ commented on README.md
> +</div>
- [ ] Kindly remove this part of the README template. You can replace it with your own logo if you have one or remove the entire( `div` tag) completely. :+1:

2023-02-14 23:21 UTC, NahnahAJ commented on README.md
> +</details>
- [ ]  This part of the section can be removed since they aren't being used in this project :+1: an alternative will be to put `N/A` in between the (`li` tags) to signify that those aren't being used in this project :wink: Any of these will be better compared to filling them with wrong or false values :100: So I will suggest that you use one of my two suggestions :smile:

2023-02-14 23:21 UTC, NahnahAJ commented on README.md
> +
- [ ] KIndly remove the second author from here since you were the sole contributor to this project.  :100:

2023-02-14 23:21 UTC, NahnahAJ commented on README.md
> +## 👥 Authors <a name="authors"></a>
- [ ] Please make this section header singular ie. `Author` since there is only one contributor in this project :wink:

2023-02-14 23:21 UTC, NahnahAJ commented on test.md
> +This file should be ignored by git.
- [ ] Lastly, as you rightly wrote here in this file, this file should be ignored by Git. Hence it shouldn't even be on GitHub so since it is here and part of your files that means it wasn't ignored. After you add this file to your `.gitignore` file, it shouldn't be pushed to github. :+1: So kindly check and fix this :wink: 
- [ ] You can read more about how `.gitignore` works [here](https://www.bmc.com/blogs/gitignore/).

2023-02-15 00:47 UTC, VelzckC0D3 commented on test.md
> +This file should be ignored by git.
Ok, thank you for your feedback, I've already doubled checked and you are right! the .gitignore wasn't working properly, I restarted the cache and modified the file, and now checking on the console with the command "git status --ignored" it shows me that both node_modules/ and test.md are ignored!

2023-02-15 01:06 UTC, AbayomiOlaoye approved these changes
Hi @VelzckC0D3 :+1: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![applause](https://user-images.githubusercontent.com/99715640/213818870-485b6c36-1d87-4b93-9a0c-ce2ae86d9a9d.gif)

## Highlights
- Great implementation of reviewer's suggestions :heavy_check_mark: 
- Good project implementation :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- You can consider checking your linters to see why it is not running. This is a very important feature in future projects.
- Also, it appears you have some merge conflict at the moment. It will be good to resolve the conflict as a professional. This speaks of your expertise with `Git` and `GitHub` .

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 01:42 UTC, merged

2023-02-15 05:08 UTC, NahnahAJ commented on test.md
> +This file should be ignored by git.
Great job finding that @VelzckC0D3 :clap: